{% set name = "pytest-memray" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_memray-{{ version }}.tar.gz
  sha256: 364152252afd563fc8b58459325f360030d2b0d5673896018a68badb35402339

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.11.1
    - hatch-vcs >=0.2
    - pip
  run:
    - python >=3.8
    - pytest >=7.2
    - memray >=1.4.1

test:
  imports:
    - pytest_memray
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A simple plugin to use with pytest
  home: https://github.com/bloomberg/pytest-memray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
