{% set name = "pytest-memray" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_memray-{{ version }}.tar.gz
  sha256: 05ec37e23c14967e02994df116bfcca26ce64a017274080c4c4e8f29818bc78a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.11.1
    - hatch-vcs >=0.2
    - pip
  run:
    - python >=3.8
    - pytest >=7.2
    - memray >=1.4.1

test:
  imports:
    - pytest_memray
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A simple plugin to use with pytest
  home: https://github.com/bloomberg/pytest-memray
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
